### ISSUE TITLE
compile libANLGeant4.so libG4tracking.so error

### ISSUE THREAD

**Issue by lichuanlong** [odakahirokazu/ComptonSoft#3]
my Geant4 is 10.03

/usr/bin/ld: aTrajectoryAllocator: TLS definition in /usr/local/lib/libG4tracking.so section .tbss mismatches non-TLS reference in CMakeFiles/ANLGeant4.dir/src/PickUpDataTrackingAction.cc.o
/usr/local/lib/libG4tracking.so: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
anlgeant4/CMakeFiles/ANLGeant4.dir/build.make:786: recipe for target 'anlgeant4/libANLGeant4.so' failed
make[2]: *** [anlgeant4/libANLGeant4.so] Error 1
CMakeFiles/Makefile2:88: recipe for target 'anlgeant4/CMakeFiles/ANLGeant4.dir/all' failed
make[1]: *** [anlgeant4/CMakeFiles/ANLGeant4.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lichuanlong** [comment]
Geant4 is GEANT4_BUILD_MULTITHREADED = ON.

Turn Off 
GEANT4_BUILD_MULTITHREADED = OFF
There is no error.

**Comment by odakahirokazu** [comment]
Thanks for trying ComptonSoft.
Yes, ComptonSoft does not support multithread mode of Geant4. Instead, you can run simulations in parallel in different independent processes (with different random seeds). You could use "parallel" (a utility library for parallel runs) from ruby/gem for this purpose.
