### ISSUE TITLE
how to run examples?

### ISSUE THREAD

**Issue by lichuanlong** [odakahirokazu/ComptonSoft#4]
I haven't used ruby before.
I have installed ComptonSoft in /usr/local.
then run simple_detector example. there is loaderror.

./run_simulation_gamma.rb 
/usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- comptonsoft/basic (LoadError)
	from /usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./run_simulation_gamma.rb:3:in `<main>'
 
How to run examples, please.

**Comment by odakahirokazu** [comment]
The system needs to know where "comptonsoft/basic.rb" is. It is normally installed into (install_prefix)/lib/ruby.

I think you need to set an environment variable RUBYLIB to the directory including it. For example, in bash:
export RUBYLIB=$RUBYLIB:(install_prefix)/lib/ruby

**Comment by lichuanlong** [comment]
Thank you.
After setting RUBYLIB, examples can run.
Is there some env setting script?

**Comment by lichuanlong** [comment]
and when plot cant find root
./plot_edep.rb 
/usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- RubyROOT (LoadError)
	from /usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./plot_edep.rb:3:in `<main>'

**Comment by lichuanlong** [comment]
OK, I haven't installed RubyROOT.
no problem.

**Comment by odakahirokazu** [comment]
Great. Actually you don't need to install RubyROOT. You can use any plotter/analyzer you like.
